### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by timofeeva16tanya** [stibiumghost/tajik-to-persian-transliteration#2]
Thank you for models and code, I interested in farsi to tajik transliteration
can you upload train.csv, dev.csv, test.csv, or write how you prepared data, please?

**Comment by stibiumghost** [comment]
Hello.
I strongly encourage you to prepare a dataset **specially** for your project so that you can prepare any new data in the same way without surprises.

You can find the aligned dataset in [data/](https://github.com/stibiumghost/tajik-to-persian-transliteration/tree/new/data). (Use [poetry_parts.csv](https://github.com/stibiumghost/tajik-to-persian-transliteration/blob/new/data/poetry_parts.csv) + [prose_parts.csv](https://github.com/stibiumghost/tajik-to-persian-transliteration/blob/new/data/prose_parts.csv) + [words.csv](https://github.com/stibiumghost/tajik-to-persian-transliteration/blob/new/data/words.csv) and split each in train (and validation?) and test sets before preprocessing/segmentation. I would not recommend using sentences/couplets from the same source in different sets.)

Look in [tg2fa_match/](https://github.com/stibiumghost/tajik-to-persian-transliteration/blob/new/tg2fa_match/match_overview.ipynb) for examples of how the data was prepared (segmented and preprocessed). Additionally, you can use [parsivar](https://github.com/ICTRC/Parsivar) to preprocess Persian texts.
